languageCode = "en-us"
title = "sherif abushadi"
baseurl = "http://sherifabushadi.com"

[params.sections.projects]
    weight=5
    enabled = false
    title = "projects"
    subtitle = '''
    Writing software is like playing with legos made of ice. If you move
    fast and don't venture too close to the sun, you can actually make progress.
    '''

[params.sections.clients]
    weight=10
    enabled = true
    title = "clients"
    subtitle = '''
    Working on tough problems with motivated teams is great fun, especially when
    the quietest person in the room speaks up and surprises us.
    '''

[params.sections.teaching]
    weight=15
    enabled = true
    title = "teaching"
    subtitle = '''
    Approaching from afar, the forest (of knowledge) appears as one thing. On arriving, many. Only then can we become the squirrel and go nuts!
    '''

[params.sections.courses]
    weight=20
    enabled = true
    title = "courses"
    subtitle = '''
    I would like my students to experience nothing less than personal transformation, to break through to a more capable version of themselves and to take refreshing naps once in a while.
    '''

[params.sections.contact]
    weight=100
    enabled=true
    title="contact"
    subtitle='''
    I'm most interested in the intersection of software and education.  The Northwest corner, specifically. Let's meet there!
    '''
    email="sherif | amgando.org"
    phone="202.299.4405"
    address="Istanbul, Turkey"

[params.social]

    title           = "Sherif Abushadi"
    image           = "http://sherifabushadi.com/images/me-website-social.png"
    description     = "Sherif Abushadi is a software developer, teacher, consultant and speaker. He thrives with his wife and daughter in Istanbul."
    url             = "http://sherifabushadi.com"
    github          = "amgando"
    twitter         = "amgando"
    twitter_domain  = "sherifabushadi.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    linkedin        = "sherifabushadi"
