languageCode = "en-us"
title = "sherif abushadi"
baseurl = "http://sherifabushadi.com"

[params.sections.projects]
    weight=5
    enabled = false
    title = "projects"
    subtitle = '''
    Writing software is like playing with legos made of ice. If you move
    fast and don't venture too close to the sun, you can actually make progress.
    '''

[params.sections.clients]
    weight=10
    enabled = true
    title = "clients"
    subtitle = '''
    Working on tough problems with a motivated team is so much fun, especially when
    the quietest person in the room surprises us with an amazing idea.
    '''

[params.sections.teaching]
    weight=15
    enabled = true
    title = "teaching"
    subtitle = '''
    From afar, the forest seems like one thing we approach. On arriving, many.
    '''

[params.sections.courses]
    weight=20
    enabled = true
    title = "courses"
    subtitle = '''
    When designing a learning experience, I want students to experience
    nothing less than personal transformation.  When learning something new myself, 
    I always look for the ticklish bits, the ideas least considered, and the 
    parts most likely to lead to a rush of late night learning fever.
    '''

[params.sections.contact]
    weight=100
    enabled=true
    title="contact"
    subtitle=""
    email="sherif | amgando.org"
    phone="202.299.4405"
    address="San Francisco, CA"

[params.social]

    title           = "Sherif Abushadi"
    image           = "http://sherifabushadi.com/images/me-website-social.png"
    description     = "Sherif Abushadi is a software developer, teacher, consultant and speaker. He thrives with his wife and daughter in San Francisco."
    url             = "http://sherifabushadi.com"
    github          = "amgando"
    twitter         = "amgando"
    twitter_domain  = "sherifabushadi.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    linkedin        = "sherifabushadi"
